@url = https://localhost:7007
@reservationId= 00000000-0000-0000-0000-000000000001
@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}/reservations
###
GET {{url}}/reservations/{{{{reservationId}}}}

###
POST {{url}}/reservations
Content-Type: application/json

{
    "ParkingSpotId": "{{parkingSpotId}}",
    "EmployeeName": "Name",
    "LicensePlate": "LicensePlate",
    "Date": "2023-09-10"

}

POST {{url}}/reservations
Content-Type: application/json

{
    "ParkingSpotId": "{{reservationId}}",
    "LicensePlate": "LicensePlate2",

}


